"""initial schema: users, interests, usage_log, feedback

Revision ID: 2a8e0edb1062
Revises: 
Create Date: 2026-07-30 11:55:09.530586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8e0edb1062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOT: bu depoda alembic bugüne kadar hiç kullanılmadı; users/interests
    # tabloları prod'da zaten auth.init_db()'nin Base.metadata.create_all()
    # çağrısıyla var. Bu ilk migration şemanın TAMAMINI (users, interests,
    # usage_log, feedback) tanımlıyor ama zaten var olan tabloları
    # `checkfirst=True` ile atlıyor -- prod'da sadece usage_log + feedback
    # gerçekten oluşturulacak. Taze bir DB'de (yerel/test) dördü de oluşur.
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if 'interests' not in existing:
        op.create_table('interests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('package', sa.String(length=64), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if 'users' not in existing:
        op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('api_key', sa.String(length=64), nullable=False),
        sa.Column('verification_credits', sa.Integer(), nullable=False),
        sa.Column('tier', sa.String(length=16), nullable=False),
        sa.Column('invite_code', sa.String(length=16), nullable=False),
        sa.Column('referred_by', sa.String(length=16), nullable=True),
        sa.Column('has_made_action', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_log_user_id'), 'usage_log', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usage_log_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usage_log_id'], ['usage_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_usage_log_id'), 'feedback', ['usage_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # users/interests bilerek DÜŞÜRÜLMÜYOR: prod'da bu migration'dan önce
    # zaten var olabilirler (create_all ile), o yüzden downgrade sadece bu
    # migration'ın kesin sahibi olduğu iki yeni tabloyu geri alıyor.
    op.drop_index(op.f('ix_feedback_usage_log_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_usage_log_user_id'), table_name='usage_log')
    op.drop_table('usage_log')
